const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const settle=async()=>{for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r));};
const script=fs.readFileSync('anki_pipeline/templates/audio-loudness.js','utf8');
function boot(support=true,fail=false){
 const dom=new JSDOM('<audio src="c.mp3" data-dictionary-accent="uk" data-dictionary-source="cambridge"></audio><audio src="o.mp3" data-dictionary-accent="uk" data-dictionary-source="oxford"></audio><audio src="w.mp3" data-dictionary-accent="us" data-dictionary-source="webster"></audio><audio src="x.mp3" data-dictionary-accent="unknown" data-dictionary-source="oxford"></audio>',{url:'http://localhost/',runScripts:'outside-only'});
 const w=dom.window,calls=[],graphs=[],gains=[];let context;
 w.HTMLMediaElement.prototype.play=function(){calls.push(this.src);return Promise.resolve();};w.HTMLMediaElement.prototype.pause=function(){};
 const node=()=>({connect(){},disconnect(){},start(){},stop(){},gain:{value:1},playbackRate:{value:1},threshold:{value:0},ratio:{value:1},knee:{value:0},attack:{value:0},release:{value:0}});
 w.fetch=async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(0)});
 if(support)w.AudioContext=class{constructor(){context=this;this.state='suspended';this.destination={};this.fail=fail;this.currentTime=0;}resume(){if(this.fail)return Promise.reject(Error('denied'));this.state='running';return Promise.resolve();}decodeAudioData(){return Promise.resolve({duration:1});}createGain(){const n=node();gains.push(n);return n;}createDynamicsCompressor(){return node();}createBufferSource(){const n=node();graphs.push(n);return n;}createMediaElementSource(){throw Error('must never reroute original media');}};
 w.eval(script);return{dom,w,calls,graphs,gains,get context(){return context;},audios:[...w.document.querySelectorAll('audio')]};
}
test('source rules amplify US once, preserve UK Cambridge and unclassified tracks',async t=>{const c=boot();t.after(()=>c.w.close());for(const a of c.audios)await a.play();await settle();assert.equal(c.calls.length,4);assert.equal(c.graphs.length,2);assert.equal(c.audios[0].getAttribute('data-loudness-rule-db'),'0');assert.equal(c.audios[1].getAttribute('data-loudness-db'),'4.4');assert.equal(c.audios[2].getAttribute('data-loudness-db'),'5.4');assert.ok(Math.abs(c.gains[1].gain.value-10**(5.4/20))<1e-10);assert.equal(c.audios[3].getAttribute('data-loudness-rule-db'),null);c.w.eval(script);await c.audios[2].play();assert.equal(c.graphs.length,3);assert.equal(c.calls.length,5);assert.equal(c.audios[2].getAttribute('src'),'w.mp3');});
test('disabling restores unity gain and volume/rate still work',async t=>{const c=boot();t.after(()=>c.w.close());await c.audios[2].play();c.w.AnkiAudioLoudness.setEnabled(false);assert.equal(c.gains[0].gain.value,1);assert.equal(c.audios[2].getAttribute('data-loudness-state'),'original');c.w.AnkiAudioLoudness.setEnabled(true);c.audios[2].volume=.4;await settle();assert.ok(Math.abs(c.gains[0].gain.value-10**(5.4/20)*.4)<1e-10);c.audios[2].playbackRate=.8;await settle();assert.equal(c.calls.length,2);assert.equal(c.audios[2].getAttribute('data-loudness-state'),'original');});
test('missing Web Audio or failed resume keeps original play in the gesture',async t=>{for(const args of [[false,false],[true,true]]){const c=boot(...args);t.after(()=>c.w.close());const p=c.audios[2].play();assert.equal(c.calls.length,1);await p;await settle();assert.equal(c.graphs.length,0);assert.equal(c.audios[2].getAttribute('data-loudness-state'),'original');}});
test('resume failure after previous amplification still has a usable ordinary media path',async t=>{const c=boot();t.after(()=>c.w.close());await c.audios[2].play();c.context.state='suspended';c.context.fail=true;await c.audios[2].play();assert.equal(c.calls.length,2);assert.equal(c.graphs.length,1);assert.equal(c.audios[2].getAttribute('data-loudness-state'),'original');});
test('same element changing to remote source after local play stays ordinary',async t=>{const c=boot();t.after(()=>c.w.close());await c.audios[2].play();c.audios[2].src='https://example.org/w.mp3';await c.audios[2].play();assert.equal(c.graphs.length,1);assert.equal(c.calls.length,2);assert.match(c.calls.at(-1),/example.org/);});
test('pause cancels a pending decode and natural end reaches original handlers',async t=>{const c=boot();t.after(()=>c.w.close());let finish;c.context;c.w.AudioContext.prototype.decodeAudioData=()=>new Promise(r=>finish=r);const p=c.audios[2].play();await settle();c.audios[2].pause();finish({duration:1});await p;assert.equal(c.graphs.length,0);c.w.AudioContext.prototype.decodeAudioData=()=>Promise.resolve({duration:1});await c.audios[1].play();let ended=0;c.audios[1].onended=()=>ended++;c.graphs[0].onended();assert.equal(ended,1);});

test('context interruption restores ordinary media at the elapsed position',async t=>{const c=boot();t.after(()=>c.w.close());await c.audios[2].play();c.context.currentTime=.3;c.context.state='suspended';c.context.onstatechange();await settle();assert.equal(c.calls.length,2);assert.equal(c.audios[2].currentTime,.3);assert.equal(c.audios[2].getAttribute('data-loudness-state'),'original');});
